<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            // ==========================================
            // ADMIN (5 user)
            // ==========================================
            [
                'name' => 'Admin Pusat',
                'password' => Hash::make('password123'),
                'id_card_number' => '100001',
                'regional_id' => 1,
                'gender' => 'male',
                'address' => 'Jl. Merdeka No. 1, Jakarta Pusat',
                'born_date' => '1990-01-15',
                'login_tokens' => null,
                'role' => 'admin',
            ],
            [
                'name' => 'Admin Selatan',
                'password' => Hash::make('password123'),
                'id_card_number' => '100002',
                'regional_id' => 2,
                'gender' => 'female',
                'address' => 'Jl. Sudirman No. 10, Jakarta Selatan',
                'born_date' => '1991-05-20',
                'login_tokens' => null,
                'role' => 'admin',
            ],
            [
                'name' => 'Admin Bandung',
                'password' => Hash::make('password123'),
                'id_card_number' => '100003',
                'regional_id' => 6,
                'gender' => 'male',
                'address' => 'Jl. Asia Afrika No. 5, Bandung',
                'born_date' => '1988-08-10',
                'login_tokens' => null,
                'role' => 'admin',
            ],
            [
                'name' => 'Admin Surabaya',
                'password' => Hash::make('password123'),
                'id_card_number' => '100004',
                'regional_id' => 10,
                'gender' => 'female',
                'address' => 'Jl. Tunjungan No. 20, Surabaya',
                'born_date' => '1992-03-25',
                'login_tokens' => null,
                'role' => 'admin',
            ],
            [
                'name' => 'Admin Semarang',
                'password' => Hash::make('password123'),
                'id_card_number' => '100005',
                'regional_id' => 12,
                'gender' => 'male',
                'address' => 'Jl. Pemuda No. 15, Semarang',
                'born_date' => '1993-11-30',
                'login_tokens' => null,
                'role' => 'admin',
            ],

            // ==========================================
            // MEDICAL (Doctor & Officer) - 24 user
            // ==========================================
            // Doctors (12 user)
            [
                'name' => 'Dr. Ahmad Fauzi',
                'password' => Hash::make('password123'),
                'id_card_number' => '200001',
                'regional_id' => 1,
                'gender' => 'male',
                'address' => 'Jl. Kesehatan No. 1, Jakarta Pusat',
                'born_date' => '1985-03-15',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Sarah Amalia',
                'password' => Hash::make('password123'),
                'id_card_number' => '200002',
                'regional_id' => 1,
                'gender' => 'female',
                'address' => 'Jl. Melati No. 5, Jakarta Pusat',
                'born_date' => '1987-07-22',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Rudi Hartono',
                'password' => Hash::make('password123'),
                'id_card_number' => '200003',
                'regional_id' => 2,
                'gender' => 'male',
                'address' => 'Jl. Mawar No. 10, Jakarta Selatan',
                'born_date' => '1986-11-08',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Maya Indah',
                'password' => Hash::make('password123'),
                'id_card_number' => '200004',
                'regional_id' => 2,
                'gender' => 'female',
                'address' => 'Jl. Anggrek No. 15, Jakarta Selatan',
                'born_date' => '1989-04-17',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Hendra Gunawan',
                'password' => Hash::make('password123'),
                'id_card_number' => '200005',
                'regional_id' => 1,
                'gender' => 'male',
                'address' => 'Jl. Kenanga No. 20, Jakarta Pusat',
                'born_date' => '1984-09-30',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Kartika Sari',
                'password' => Hash::make('password123'),
                'id_card_number' => '200006',
                'regional_id' => 1,
                'gender' => 'female',
                'address' => 'Jl. Dahlia No. 25, Jakarta Pusat',
                'born_date' => '1988-12-12',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Lukman Hakim',
                'password' => Hash::make('password123'),
                'id_card_number' => '200007',
                'regional_id' => 6,
                'gender' => 'male',
                'address' => 'Jl. Pasteur No. 30, Bandung',
                'born_date' => '1983-06-22',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Nina Marlina',
                'password' => Hash::make('password123'),
                'id_card_number' => '200008',
                'regional_id' => 6,
                'gender' => 'female',
                'address' => 'Jl. Dago No. 35, Bandung',
                'born_date' => '1990-02-14',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Purnomo Adi',
                'password' => Hash::make('password123'),
                'id_card_number' => '200009',
                'regional_id' => 10,
                'gender' => 'male',
                'address' => 'Jl. Darmo No. 40, Surabaya',
                'born_date' => '1982-08-05',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Ratna Dewi',
                'password' => Hash::make('password123'),
                'id_card_number' => '200010',
                'regional_id' => 12,
                'gender' => 'female',
                'address' => 'Jl. Simpang Lima No. 45, Semarang',
                'born_date' => '1986-01-30',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Surya Utama',
                'password' => Hash::make('password123'),
                'id_card_number' => '200011',
                'regional_id' => 12,
                'gender' => 'male',
                'address' => 'Jl. Gajah Mada No. 50, Semarang',
                'born_date' => '1985-05-20',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Dr. Taufik Hidayat',
                'password' => Hash::make('password123'),
                'id_card_number' => '200012',
                'regional_id' => 1,
                'gender' => 'male',
                'address' => 'Jl. Tangerang Raya No. 55, Jakarta Pusat',
                'born_date' => '1987-11-10',
                'login_tokens' => null,
                'role' => 'medical',
            ],

            // Officers (12 user)
            [
                'name' => 'Petugas Budi Waluyo',
                'password' => Hash::make('password123'),
                'id_card_number' => '300001',
                'regional_id' => 1,
                'gender' => 'male',
                'address' => 'Jl. Petugas No. 1, Jakarta Pusat',
                'born_date' => '1993-06-12',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Citra Dewi',
                'password' => Hash::make('password123'),
                'id_card_number' => '300002',
                'regional_id' => 1,
                'gender' => 'female',
                'address' => 'Jl. Petugas No. 2, Jakarta Pusat',
                'born_date' => '1994-12-05',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Dodi Supriadi',
                'password' => Hash::make('password123'),
                'id_card_number' => '300003',
                'regional_id' => 2,
                'gender' => 'male',
                'address' => 'Jl. Petugas No. 3, Jakarta Selatan',
                'born_date' => '1992-08-19',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Eka Putri',
                'password' => Hash::make('password123'),
                'id_card_number' => '300004',
                'regional_id' => 2,
                'gender' => 'female',
                'address' => 'Jl. Petugas No. 4, Jakarta Selatan',
                'born_date' => '1995-03-28',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Fajar Nugroho',
                'password' => Hash::make('password123'),
                'id_card_number' => '300005',
                'regional_id' => 1,
                'gender' => 'male',
                'address' => 'Jl. Petugas No. 5, Jakarta Pusat',
                'born_date' => '1991-10-14',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Gilang Ramadhan',
                'password' => Hash::make('password123'),
                'id_card_number' => '300006',
                'regional_id' => 1,
                'gender' => 'male',
                'address' => 'Jl. Petugas No. 6, Jakarta Pusat',
                'born_date' => '1993-07-30',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Heri Susanto',
                'password' => Hash::make('password123'),
                'id_card_number' => '300007',
                'regional_id' => 6,
                'gender' => 'male',
                'address' => 'Jl. Petugas No. 7, Bandung',
                'born_date' => '1992-04-15',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Indra Kusuma',
                'password' => Hash::make('password123'),
                'id_card_number' => '300008',
                'regional_id' => 6,
                'gender' => 'male',
                'address' => 'Jl. Petugas No. 8, Bandung',
                'born_date' => '1994-09-22',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Joko Widodo',
                'password' => Hash::make('password123'),
                'id_card_number' => '300009',
                'regional_id' => 10,
                'gender' => 'male',
                'address' => 'Jl. Petugas No. 9, Surabaya',
                'born_date' => '1991-01-18',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Kurniawan Adi',
                'password' => Hash::make('password123'),
                'id_card_number' => '300010',
                'regional_id' => 12,
                'gender' => 'male',
                'address' => 'Jl. Petugas No. 10, Semarang',
                'born_date' => '1993-05-25',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Lestari Wati',
                'password' => Hash::make('password123'),
                'id_card_number' => '300011',
                'regional_id' => 12,
                'gender' => 'female',
                'address' => 'Jl. Petugas No. 11, Semarang',
                'born_date' => '1995-11-08',
                'login_tokens' => null,
                'role' => 'medical',
            ],
            [
                'name' => 'Petugas Maman Abdurahman',
                'password' => Hash::make('password123'),
                'id_card_number' => '300012',
                'regional_id' => 1,
                'gender' => 'male',
                'address' => 'Jl. Petugas No. 12, Jakarta Pusat',
                'born_date' => '1992-02-28',
                'login_tokens' => null,
                'role' => 'medical',
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->insert(array_merge($user, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
